<a href="https://colab.research.google.com/github/ssfatemi/DL-ML-Tutorial/blob/main/ML-python/4-saving-models/Model_saving.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Saving trained models
## 2 solutions
1- pickle,
2- sklearn joblib


## Training the model

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
df = pd.read_csv("homeprices.csv")
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)
model.predict([[5000]])


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([913240.11571842])

## Save/ load using pickle

In [2]:
# save

import pickle
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [3]:
# load

import pickle
with open('model_pickle','rb') as file:
    mp = pickle.load(file)
mp.predict([[5000]])


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([913240.11571842])

## Save/ load using joblib
More efficient for models with large np arrays

In [5]:
# save the model

import joblib
joblib.dump(model, 'model_joblib')


['model_joblib']

In [6]:
#load the model

import joblib
mj = joblib.load('model_joblib')
mj.predict([[5000]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([913240.11571842])